# -*- coding: utf-8 -*-
# 从 Excel 构建的 step3_data
# 第132行及以上的数据 + 第132行以后的数据（步骤信息数据段）

step3_data_list = [
    # === 第132行及以上的数据（step2_data） ===
    ('四步骤方案', '无方案'),
    ('url: alterJCSTPNRC.jsp', 'url: alterJCSTPNRC.jsp'),
    ('woRid: 13757566', 'woRid: 13757566'),
    ('planStartDate: 2026-01-05', 'planStartDate: 2026-01-05'),
    ('wgp: 3_CABIN_TPG', 'wgp: 3_CABIN_TPG'),
    ('workorder: 120000588122', 'workorder: 120000588122'),
    ('tailno: A6-EGB', 'tailno: A6-EGB'),
    ('jcMode: E', 'jcMode: E'),
    ('jcVid: 13', 'jcVid: 1'),
    ('jcSite: HG', 'jcSite: HG'),
    ('booth: A11', 'booth: A11'),
    ('txtMessage:', 'txtMessage:'),
    ('ownerCode: EK', 'ownerCode: EK'),
    ('flightCheckNo: 5C', 'flightCheckNo: 5C'),
    ('strWorkGroupRii: Y', 'strWorkGroupRii: Y'),
    ('station: CAN', 'station: CAN'),
    ('delrid:', 'delrid:'),
    ('updjobcard: false', 'updjobcard: false'),
    ('originalStatus:', 'originalStatus:'),
    ('woStatus: N', 'woStatus: N'),
    ('jcStatus: N', 'jcStatus: N'),
    ('primaryJC: 13011601', 'primaryJC: 13034743'),
    ('addJC:', 'addJC:'),
    ('printed:', 'printed:'),
    ('jcType: NR', 'jcType: NR'),
    ('jobcard: NR/000000290', 'jobcard: NR/000001196'),
    ('jcSeq: 50290', 'jcSeq: 51196'),
    ('workgroup: 3_CABIN_TPG', 'workgroup: 3_CABIN_TPG'),
    ('corrosion:', 'corrosion:'),
    ('eSign:', 'eSign:'),
    ('flagCmt: Y', 'flagCmt: Y'),
    ('customerNo:', 'customerNo:'),
    ('strCsnJcWorkOrder:', 'strCsnJcWorkOrder:'),
    ('jcdesc:', 'jcdesc:'),
    ('mainlabor:', 'mainlabor:'),
    ('rii: N', 'rii:'),
    ('jcendesc: REPAINT CABIN LAVATORY TOILET SHROUD SURROUND,LOC:A B C D E F G H P N R S', 'jcendesc: SPARE CABIN PARTS'),
    ('transferRemark: 添加航材', 'transferRemark:'),
    ('jcRemark:', 'jcRemark:'),
    ('slnReqDate:', 'slnReqDate:'),
    ('slnSchedFinish:', 'slnSchedFinish:'),
    ('slnStatus: Y', 'slnStatus: N'),
    ('slnCoordinator:', 'slnCoordinator:'),
    ('jc_workorder: 500007966298', 'jc_workorder: 500007984729'),
    ('customer_jc:', 'customer_jc:'),
    ('all_N: 全选N', 'all_N: 全选N'),
    ('all_N: 取消判断', 'all_N: 取消判断'),
    ('majorMdo: N', 'majorMdo:'),
    ('pse: N', 'pse:'),
    ('external: N', 'external:'),
    ('outOfManual: N', 'outOfManual:'),
    ('authApp: N', 'authApp:'),
    ('exteriorDamage: N', 'exteriorDamage:'),
    ('appRef:', 'appRef:'),
    ('engSign: 007581 HU HONGWEI', 'engSign:'),
    ('engSignDate: 2026-01-06', 'engSignDate:'),
    ('referenceDesc: CMM 25-46-83 REV.26', 'referenceDesc:'),
    ('forbidEsign:', 'forbidEsign:'),
    ('inspector: 007581 HU HONGWEI', 'inspector: 007548 LIU FAN'),
    ('createdDate: 2026-01-06', 'createdDate: 2026-01-13'),
    ('nrcTpgEva:', 'nrcTpgEva:'),
    ('strRiiFlag: 2', 'strRiiFlag: 2'),
    ('nrcTpgEvaRemark:', 'nrcTpgEvaRemark:'),
    ('engSlnRcpDate:', 'engSlnRcpDate:'),
    ('engRsn:', 'engRsn:'),
    ('printer: \lx-ps01\Prt2N15M非例卡(机上客舱2车间)', 'printer: \lx-ps01\Prt2N15M非例卡(机上客舱2车间)'),
    ('cb_prt_mat:', 'cb_prt_mat:'),

    # === 第132行以后的数据（步骤信息数据段） ===
    ('eSignInfo', ''),
    ('StepStatus', 'Y'),
    ('stepDesc', ''),
    ('flagEr', 'N'),
    ('stepEnDesc', 'REFER TO CMM 25-46-83 REV.26,REMOVE CABIN LAVATORY TOILET SHROUD SURROUND,LOC:A B C D E F G H P N R S'),
    ('schedphase', '阶段2-修理'),
    ('schedtrade', 'TRIM'),
    ('schedlabor', '1'),
    ('schedmh', '12.0'),
    ('schedzone', '客舱'),
    ('remark', ''),
    ('primary', '19600800'),
    ('updatedBy', '007581 HU HONGWEI'),
    ('editorGrp', '3_CABIN_TPG'),
    ('step', '1'),
    ('isupd', 'false'),
    ('onlyUpdStep', 'false'),
    ('stepVid', '2'),
    ('stepRii', 'N'),
    ('taskDsc', ''),
    ('flagTank', 'N'),
    ('eSignInfo', ''),
    ('StepStatus', 'Y'),
    ('stepDesc', ''),
    ('flagEr', 'N'),
    ('stepEnDesc', 'REFER TO AMM TASK 25-00-00-370-801 REV.___,REPAIR CABIN LAVATORY TOILET SHROUD SURROUND,LOC:A B C D E F G H P N R S'),
    ('schedphase', '阶段2-修理'),
    ('schedtrade', 'HM3_CABIN'),
    ('schedlabor', '3'),
    ('schedmh', '12.0'),
    ('schedzone', '客舱'),
    ('remark', ''),
    ('primary', '19600801'),
    ('updatedBy', '007581 HU HONGWEI'),
    ('editorGrp', '3_CABIN_TPG'),
    ('step', '2'),
    ('isupd', 'false'),
    ('onlyUpdStep', 'false'),
    ('stepVid', '2'),
    ('stepRii', 'N'),
    ('taskDsc', ''),
    ('flagTank', 'N'),
    ('eSignInfo', ''),
    ('StepStatus', 'N'),
    ('stepDesc', ''),
    ('flagEr', 'N'),
    ('stepEnDesc', 'REFER TO AMM TASK 25-00-00-370-801 REV.___,APPLY PAINT TO CABIN LAVATORY TOILET SHROUD SURROUND,LOC:A B C D E F G H P N R S'),
    ('schedphase', '阶段2-修理'),
    ('schedtrade', 'CABIN_PNT'),
    ('schedlabor', '4'),
    ('schedmh', '12.0'),
    ('schedzone', '客舱'),
    ('remark', ''),
    ('primary', '19600802'),
    ('updatedBy', '007581 HU HONGWEI'),
    ('editorGrp', '3_CABIN_TPG'),
    ('step', '3'),
    ('isupd', 'false'),
    ('onlyUpdStep', 'false'),
    ('stepVid', '6'),
    ('stepRii', 'N'),
    ('taskDsc', ''),
    ('flagTank', 'N'),
    ('eSignInfo', ''),
    ('StepStatus', 'N'),
    ('stepDesc', ''),
    ('flagEr', 'N'),
    ('stepEnDesc', 'REFER TO CMM 25-46-83 REV.26,INSTALL CABIN LAVATORY TOILET SHROUD SURROUND,LOC:A B C D E F G H P N R S'),
    ('schedphase', '阶段2-修理'),
    ('schedtrade', 'TRIM'),
    ('schedlabor', '2'),
    ('schedmh', '6.0'),
    ('schedzone', '客舱'),
    ('remark', ''),
    ('primary', '19600835'),
    ('updatedBy', '007581 HU HONGWEI'),
    ('editorGrp', '3_CABIN_TPG'),
    ('step', '4'),
    ('isupd', 'false'),
    ('onlyUpdStep', 'false'),
    ('stepVid', '2'),
    ('stepRii', 'N'),
    ('taskDsc', ''),
    ('flagTank', 'N'),
    ('checkStepExist: true', 'checkStepExist:'),
    ('txtMenuID: 22800', 'txtMenuID: 22800'),
    ('nrcHdPrt:', 'nrcHdPrt:'),
]
