"""add_4_columns_to_import_batch_item

Revision ID: 156d20ab3d58
Revises: 1bfcf4d801bd
Create Date: 2025-12-10 12:19:02.401148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156d20ab3d58'
down_revision = '1bfcf4d801bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batch_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_workcard_number', sa.String(length=100), nullable=True, comment='相关工卡号 (txtCRN)'))
        batch_op.add_column(sa.Column('reference_workcard_item', sa.String(length=100), nullable=True, comment='相关工卡序号 (refNo)'))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True, comment='区域 (txtZoneName)'))
        batch_op.add_column(sa.Column('zone_number', sa.String(length=100), nullable=True, comment='区域号 (txtZoneTen)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batch_items', schema=None) as batch_op:
        batch_op.drop_column('zone_number')
        batch_op.drop_column('area')
        batch_op.drop_column('reference_workcard_item')
        batch_op.drop_column('reference_workcard_number')

    # ### end Alembic commands ###