"""Add issued_workcard_number

Revision ID: 1bfcf4d801bd
Revises: 008
Create Date: 2025-12-10 00:57:52.333053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfcf4d801bd'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Simplified content to avoid SQLite constraint naming issues
    with op.batch_alter_table('import_batch_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issued_workcard_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcards_second_level_subcomponent'))
        batch_op.drop_index(batch_op.f('ix_workcards_msn'))
        batch_op.drop_index(batch_op.f('ix_workcards_main_component'))
        batch_op.drop_index(batch_op.f('ix_workcards_main_area'))
        batch_op.drop_index(batch_op.f('ix_workcards_first_level_subcomponent'))
        batch_op.drop_index(batch_op.f('ix_workcards_amm_ipc_eff'))
        batch_op.drop_index(batch_op.f('ix_workcards_aircraft_type'))
        batch_op.drop_index(batch_op.f('ix_workcards_aircraft_number'))
        batch_op.drop_index('idx_config_cleaned')
        batch_op.drop_index('idx_aircraft_config')

    with op.batch_alter_table('workcard_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_workcard_types_name', ['name'], unique=False)

    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'defect_lists', ['defect_list_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('import_batch_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'defect_records', ['defect_record_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('issued_workcard_number')

    with op.batch_alter_table('defect_cleaned_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_cleaned_data_second_level_subcomponent'))

    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_configurations_name', ['name'], unique=False)
        batch_op.alter_column('field_mapping',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###