"""add_defect_schemes_tables

Revision ID: 594eb1579e1d
Revises: 010_defect_list_index
Create Date: 2026-03-07 09:19:29.022526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594eb1579e1d'
down_revision = '010_defect_list_index'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_pn', sa.String(length=50), nullable=False, comment='部件件号'),
    sa.Column('defect_catalog', sa.Integer(), nullable=False, comment='缺陷分类号'),
    sa.Column('jc_desc_cn', sa.Text(), nullable=True, comment='标准缺陷描述(中文)'),
    sa.Column('jc_desc_en', sa.Text(), nullable=True, comment='标准缺陷描述(英文)'),
    sa.Column('key_words_1', sa.String(length=100), nullable=True, comment='关键词1'),
    sa.Column('key_words_2', sa.String(length=100), nullable=True, comment='关键词2'),
    sa.Column('trade', sa.String(length=50), nullable=True, comment='工种'),
    sa.Column('zone', sa.String(length=50), nullable=True, comment='区域'),
    sa.Column('loc', sa.String(length=100), nullable=True, comment='位置'),
    sa.Column('qty', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('jc_type', sa.String(length=50), nullable=True, comment='工卡类型'),
    sa.Column('labor', sa.Float(), nullable=True, comment='人工'),
    sa.Column('manhour', sa.Float(), nullable=True, comment='总工时'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp_pn', 'defect_catalog', name='uix_comp_pn_catalog')
    )
    with op.batch_alter_table('defect_schemes', schema=None) as batch_op:
        batch_op.create_index('idx_scheme_search', ['comp_pn', 'key_words_1', 'key_words_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_schemes_comp_pn'), ['comp_pn'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_schemes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_schemes_key_words_1'), ['key_words_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_schemes_key_words_2'), ['key_words_2'], unique=False)

    op.create_table('defect_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='步骤号'),
    sa.Column('step_desc', sa.Text(), nullable=True, comment='工序指导(中文)'),
    sa.Column('step_desc_en', sa.Text(), nullable=True, comment='工序指导(英文)'),
    sa.Column('manhour', sa.Float(), nullable=True, comment='步骤工时'),
    sa.ForeignKeyConstraint(['scheme_id'], ['defect_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_steps', schema=None) as batch_op:
        batch_op.create_index('idx_scheme_step', ['scheme_id', 'step_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_steps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_steps_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('defect_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False, comment='航材件号'),
    sa.Column('amount', sa.Float(), nullable=True, comment='数量'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['step_id'], ['defect_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_materials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_materials_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_materials_step_id'), ['step_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_materials_step_id'))
        batch_op.drop_index(batch_op.f('ix_defect_materials_part_number'))
        batch_op.drop_index(batch_op.f('ix_defect_materials_id'))

    op.drop_table('defect_materials')
    with op.batch_alter_table('defect_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_steps_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_defect_steps_id'))
        batch_op.drop_index('idx_scheme_step')

    op.drop_table('defect_steps')
    with op.batch_alter_table('defect_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_schemes_key_words_2'))
        batch_op.drop_index(batch_op.f('ix_defect_schemes_key_words_1'))
        batch_op.drop_index(batch_op.f('ix_defect_schemes_id'))
        batch_op.drop_index(batch_op.f('ix_defect_schemes_comp_pn'))
        batch_op.drop_index('idx_scheme_search')

    op.drop_table('defect_schemes')
    # ### end Alembic commands ###
