"""add_candidate_description_en_to_import_batch_item

Revision ID: 8dfc709c65d2
Revises: a1b2c3d4e5f6
Create Date: 2025-12-29 15:40:01.971883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfc709c65d2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batch_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_description_en', sa.Text(), nullable=True, comment='历史工卡描述（英文），来自Excel的 Candidate Workcard Description (English) 列'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batch_items', schema=None) as batch_op:
        batch_op.drop_column('candidate_description_en')

    # ### end Alembic commands ###