"""add_candidate_history_wo_and_refer_manual

Revision ID: db574b6a01b8
Revises: 594eb1579e1d
Create Date: 2026-03-07 09:30:27.370737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db574b6a01b8'
down_revision = '594eb1579e1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_schemes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_history_wo', sa.String(length=100), nullable=True, comment='候选历史工卡指令号'))
        batch_op.add_column(sa.Column('refer_manual', sa.String(length=100), nullable=True, comment='参考工卡'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_schemes', schema=None) as batch_op:
        batch_op.drop_column('refer_manual')
        batch_op.drop_column('candidate_history_wo')

    # ### end Alembic commands ###