"""add local wash tables

Revision ID: ed180cc8eaa5
Revises: c345e357ec5e
Create Date: 2025-12-24 16:13:32.298996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed180cc8eaa5'
down_revision = 'c345e357ec5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_id', 'version', name='uq_keyword_dict_configuration_version')
    )
    with op.batch_alter_table('keyword_dict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_dict_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_id'), ['id'], unique=False)

    op.create_table('keyword_dict_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('main_component', sa.String(length=200), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dict_id'], ['keyword_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_dict_item', schema=None) as batch_op:
        batch_op.create_index('idx_keyword_dict_item_dict_dim_main', ['dict_id', 'dimension', 'main_component'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_item_dict_id'), ['dict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_item_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_item_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_item_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_item_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_dict_item_main_component'), ['main_component'], unique=False)

    op.create_table('workcard_clean_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workcard_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('dict_version', sa.String(length=50), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_cn', sa.Text(), nullable=True),
    sa.Column('workcard_number', sa.String(length=50), nullable=True),
    sa.Column('main_component', sa.String(length=200), nullable=True),
    sa.Column('sub_component', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('orientation', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['dict_id'], ['keyword_dict.id'], ),
    sa.ForeignKeyConstraint(['workcard_id'], ['workcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workcard_clean_local', schema=None) as batch_op:
        batch_op.create_index('idx_workcard_clean_local_cfg_dict', ['configuration_id', 'dict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_aircraft_type'), ['aircraft_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_dict_id'), ['dict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_main_component'), ['main_component'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_orientation'), ['orientation'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_sub_component'), ['sub_component'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_workcard_id'), ['workcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcard_clean_local_workcard_number'), ['workcard_number'], unique=False)

    op.create_table('defect_clean_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_record_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('dict_version', sa.String(length=50), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_cn', sa.Text(), nullable=True),
    sa.Column('main_component', sa.String(length=200), nullable=True),
    sa.Column('sub_component', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('orientation', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['defect_record_id'], ['defect_records.id'], ),
    sa.ForeignKeyConstraint(['dict_id'], ['keyword_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_clean_local', schema=None) as batch_op:
        batch_op.create_index('idx_defect_clean_local_cfg_dict', ['configuration_id', 'dict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_aircraft_type'), ['aircraft_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_defect_record_id'), ['defect_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_dict_id'), ['dict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_main_component'), ['main_component'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_orientation'), ['orientation'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_clean_local_sub_component'), ['sub_component'], unique=False)

    op.create_table('defect_match_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_record_id', sa.Integer(), nullable=False),
    sa.Column('workcard_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('dict_version', sa.String(length=50), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_cn', sa.Text(), nullable=True),
    sa.Column('workcard_number', sa.String(length=50), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_main', sa.Float(), nullable=False),
    sa.Column('score_sub', sa.Float(), nullable=False),
    sa.Column('score_location', sa.Float(), nullable=False),
    sa.Column('score_orientation', sa.Float(), nullable=False),
    sa.Column('score_status', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['defect_record_id'], ['defect_records.id'], ),
    sa.ForeignKeyConstraint(['dict_id'], ['keyword_dict.id'], ),
    sa.ForeignKeyConstraint(['workcard_id'], ['workcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_match_local', schema=None) as batch_op:
        batch_op.create_index('idx_defect_match_local_defect_cfg', ['defect_record_id', 'configuration_id'], unique=False)
        batch_op.create_index('idx_defect_match_local_score', ['score_total'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_aircraft_type'), ['aircraft_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_defect_record_id'), ['defect_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_dict_id'), ['dict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_workcard_id'), ['workcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_match_local_workcard_number'), ['workcard_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_match_local', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_match_local_workcard_number'))
        batch_op.drop_index(batch_op.f('ix_defect_match_local_workcard_id'))
        batch_op.drop_index(batch_op.f('ix_defect_match_local_id'))
        batch_op.drop_index(batch_op.f('ix_defect_match_local_dict_id'))
        batch_op.drop_index(batch_op.f('ix_defect_match_local_defect_record_id'))
        batch_op.drop_index(batch_op.f('ix_defect_match_local_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_defect_match_local_aircraft_type'))
        batch_op.drop_index('idx_defect_match_local_score')
        batch_op.drop_index('idx_defect_match_local_defect_cfg')

    op.drop_table('defect_match_local')
    with op.batch_alter_table('defect_clean_local', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_sub_component'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_status'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_orientation'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_main_component'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_location'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_id'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_dict_id'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_defect_record_id'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_defect_clean_local_aircraft_type'))
        batch_op.drop_index('idx_defect_clean_local_cfg_dict')

    op.drop_table('defect_clean_local')
    with op.batch_alter_table('workcard_clean_local', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_workcard_number'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_workcard_id'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_sub_component'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_status'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_orientation'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_main_component'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_location'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_id'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_dict_id'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_workcard_clean_local_aircraft_type'))
        batch_op.drop_index('idx_workcard_clean_local_cfg_dict')

    op.drop_table('workcard_clean_local')
    with op.batch_alter_table('keyword_dict_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_dict_item_main_component'))
        batch_op.drop_index(batch_op.f('ix_keyword_dict_item_keyword'))
        batch_op.drop_index(batch_op.f('ix_keyword_dict_item_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_dict_item_enabled'))
        batch_op.drop_index(batch_op.f('ix_keyword_dict_item_dimension'))
        batch_op.drop_index(batch_op.f('ix_keyword_dict_item_dict_id'))
        batch_op.drop_index('idx_keyword_dict_item_dict_dim_main')

    op.drop_table('keyword_dict_item')
    with op.batch_alter_table('keyword_dict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_dict_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_dict_configuration_id'))

    op.drop_table('keyword_dict')
    # ### end Alembic commands ###